// IMAGENES INTERACTIVAS / ARRASTRABLES DEL HOME ALTERNATIVO
const interactiveImgs = [ //Creamos un array que guarda nuestras imagenes
    './img/1.jpg',
    './img/2.jpg',
    './img/3.jpg',
    './img/4.jpg',
    './img/5.jpg',
    './img/6.jpg',
    './img/7.jpg',
    './img/8.jpg',
    './img/9.jpg'
];

// INFORMACIÓN DEL CATÁLOGO DE PELÍCULAS
const moviesSC = [
    {
        id: 0, 
        name: "Priscilla",
        movieCover: "img/portada0.jpg",
        year: 2023,
        gallery: ["img/priscila8.jpg", "img/priscila10.jpg", "img/priscila9.jpg", "img/priscila12.jpg", "img/priscila1.jpg", "img/priscila14.jpg", "img/priscila17.jpg", "img/priscila2.jpg"],
        duration: "108 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola"],
        production: ["A24", " Stage 6 Films"],
        genre: "Película",
        cast: ["Cailee Spaeny", "Jacob Elordi", "Ari Cohen"],
    synopsis: "Cuando Priscilla Beaulieu conoce a Elvis Presley, el hombre que ya es una superestrella del rock and roll, se convierte en alguien totalmente inesperado: un enamoramiento emocionante, un aliado en la soledad, un mejor amigo vulnerable.",
    },

    {
        id: 1, 
        name: "En las Rocas",
        movieCover: "img/portada1.jpg",
        year: 2020,
        gallery: ["img/block6.jpg", "img/block7.jpg", "img/block3.jpg", "img/block2.jpg", "img/block9.jpg", "img/block1.jpg", "img/block4.jpg", "img/block11.jpg"],
        duration: "96 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: "Sofia Coppola",
        production: ["A24", " AppleTV+"],
        genre: "Película",
        cast: ["Bill Murray", "Rashida Jones", "Marlon Wayans"],
        synopsis: "Llena de dudas sobre su matrimonio, una joven neoyorquina decide seguir a su marido con ayuda de su excéntrico y mujeriego padre.",
    },

    {
        id: 2, 
        name: "El seductor",
        movieCover: "img/portada2.jpg",
        year: 2017,
        gallery: ["img/beguiled10.jpg", "img/beguiled2.jpg", "img/beguiled1.jpg","img/beguiled6.jpg", "img/beguiled5.jpg", "img/beguiled3.jpg", "img/beguiled9.jpg", "img/beguiled8.jpg"],
        duration: "91 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola"],
        production: ["American Zoetrope", " FR Productions"],
        genre: "Película",
        cast: ["Colin Farrell", "Nicole Kidman", "Kirsten Dunst", "Elle Fanning"],
        synopsis: "La llegada inesperada de un soldado de la Unión herido a una escuela femenina en Virginia durante la guerra civil estadounidense provoca celos y traiciones.",
    },

    {
        id: 3, 
        name: "A Very Murray Christmas",
        movieCover: "img/portada3.jpg",
        year: 2015,
        gallery: ["img/murray4.jpg", "img/murray5.jpg", "img/murray7.jpg", "img/murray2.jpg", "img/murray3.jpg", "img/murray8.jpg", "img/murray1.jpg", "img/murray6.jpg"],
        duration: "56 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola", " Mitch Glazer", " Bill Murray"],
        production: ["American Zoetrope", " Netflix"],
        genre: "Película",
        cast: ["Bill Murray", "Miley Cyrus", "George Clooney"],
        synopsis: "Bill Murray reúne a un elenco estelar para una clásica velada decembrina, donde la fraternidad fluye de los tragos y cantos que harán de esta una blanca Navidad.",
    },

    {
        id: 4,  
        name: "Ladrones de la Fama",
        movieCover: "img/portada4.jpg",
        year: 2013,
        gallery: ["img/bling13.jpg", "img/bling19.jpg", "img/bling3.jpg", "img/bling5.jpg", "img/bling11.jpg", "img/bling9.jpg", "img/bling8.jpg", "img/bling1.jpg"],
        duration: "87 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: "Sofia Coppola",
        production: ["American Zoetrope", " NALA Films", " Pathé Distribution"],
        genre: "Película",
        cast: ["Emma Watson", "Israel Broussard", "Katie Chang"],
        synopsis: "Basada en hechos reales, un grupo de adolescentes obsesionados con la fama usa Internet para encontrar a famosos y robar en sus hogares.",
    },

    {
        id: 5, 
        name: "Somewhere: en un rincón del corazón",
        movieCover: "img/portada5.jpg",
        year: 2010,
        gallery:["img/somewhere6.jpg", "img/somewhere3.jpg", "img/somewhere5.jpg", "img/somewhere4.jpg", "img/somewhere1.jpg", "img/somewhere2.jpg", "img/somewhere7.jpg", "img/somewhere8.jpg"],
        duration: "98 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: "Sofia Coppola",
        production: ["Focus Features", " Pathé Films", " Medusa Produzione", " Tohokushinsha Film Corporation (TFC)", " American Zoetrope"],
        genre: "Película",
        cast: ["Elle Fanning", "Stephen Dorff", "Chris Pontius"],
        synopsis: "Después de salir del Chateau Marmont, un actor de Hollywood desilusionado se replantea su vida cuando su hija de once años le sorprende con una visita.",
    },

    {
        id: 6, 
        name: "Maria Antonieta",
        movieCover: "img/portada6.jpg",
        year: 2006,
        gallery: ["img/marie9.jpg", "img/marie8.jpg", "img/marie5.jpg", "img/marie4.jpg", "img/marie6.jpg", "img/marie1.jpg", "img/marie7.jpg", "img/marie2.jpg"],
        duration: "124 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: "Sofia Coppola",
        production: ["Columbia Pictures"," American Zoetrope"],
        genre:  "Película",
        cast: ["Kirsten Dunst", "Jason Schwartzman", "Rip Torn"],
        synopsis: "El relato de la emblemática pero malograda reina de Francia, María Antonieta. Desde sus esponsales y su matrimonio con Luis XVI a los 14 años hasta su reinado a los 19 años y el final de su reinado, y finalmente la caída de Versalles.",
    },

    {
        id: 7,
        name: "Perdidos en Tokio",
        movieCover: "img/portada7.jpg",
        year: 2003,
        gallery: ["img/lost6.jpg", "img/lost4.jpg", "img/lost7.jpg", "img/lost3.jpg", "img/lost5.jpg", "img/lost1.jpg", "img/lost2.jpg", "img/lost8.jpg"],
        duration: "105 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: "Sofia Coppola",
        production: ["Focus Features"," American Zoetrope", " Elemental Films"],
        genre: "Película",
        cast: ["Bill Murray", "Scarlett Johansson", "Giovanni Ribisi"],
        synopsis: "Dos solitarios turistas —la esposa ignorada de un fotógrafo y una estrella de cine en su ocaso— encuentran consuelo haciéndose compañía el uno al otro en la bulliciosa Tokio.",
    },

    {
        id: 8, 
        name: "Las virgenes suicidas",
        movieCover: "img/portada8.jpg",
        year: 1999,
        gallery:["img/virgin5.jpg", "img/virgin2.jpg", "img/virgin4.jpg", "img/virgin7.jpg", "img/virgin3.jpg", "img/virgin8.jpg", "img/virgin1.jpg", "img/virgin6.jpg"],
        duration: "97 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola"],
        production: ["American Zoetrope", " Muse Productions", " Eternity Pictures"],
        genre:"Película",
        cast: ["Kirsten Dunst", "Josh Hartnett", "James Wood"],
        synopsis: "A mediados de los '70, en una tranquila comunidad de Michigan, viven las hermanas Lisbon, cinco adolescentes cuya belleza ha cautivado a un grupo de muchachos del pueblo.",
    },

    {
        id: 9, 
        name: "Lick the Star",
        movieCover: "img/portada9.jpg",
        year: 1998,
        gallery:["img/lick1.jpg", "img/lick6.png", "img/lick2.jpg", "img/lick5.png", "img/lick4.png", "img/lick3.png", "img/lick7.png", "img/lick8.png"],
        duration: "14 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola", " Stephanie Hayman"],
        production: ["Sofia Coppola"],
        genre:"Cortometraje",
        cast: ["Christina Turley", "Audrey Heaven", "Robert Schwartzman"],
        synopsis: "Un grupo de chicas de secundaria que conspiran para envenenar a los chicos de su escuela.",
    },

    {
        id: 10, 
        name: "New York City Ballet",
        movieCover: "img/portada10.jpg",
        year: 2021,
        gallery: ["img/ballet1.jpg", "img/ballet2.jpg", "img/ballet3.jpg", "img/ballet4.jpg", "img/ballet5.jpg", "img/ballet6.jpg", "img/ballet7.jpg", "img/ballet8.jpg"],
        duration: "25 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Sofia Coppola", " Justin Peck"],
        production: ["New York City Ballet"],
        genre:"Documental",
        cast: ["Maria Kowroski", "Ron Wasserman", "Tiler Peck"],
        synopsis: "Corto dirigido por Sofia Coppola para la Gala de Primavera de Nueva York.",
    },

    {
        id: 11, 
        name: "The Chanel Iconic",
        movieCover: "img/portada11.jpg",
        year: 2021,
        gallery:["img/chanel1.png", "img/chanel2.png", "img/chanel3.png", "img/chanel4.png", "img/chanel5.png", "img/chanel6.png", "img/chanel7.png", "img/chanel8.png"],
        duration: "1 minuto",
        country: "Francia",
        director: "Sofia Coppola",
        screenwriter:["Desconocido"],
        production: ["Chanel"],
        genre:"Corto Publicitario",
        cast: ["Zoé Adjani", "Carole Bouquet", "Anna Mouglalis", "Iman Perez"],
        synopsis: "Dos spots para Chanel dirigidos por Sofia Coppola.",
    },

     {
        id: 12,  
        name: "In Homage to Mademoiselle",
        movieCover: "img/portada12.jpg",
        year: 2019,
        gallery:["img/homage1.png", "img/homage2.png", "img/homage3.png", "img/homage4.png", "img/homage5.png", "img/homage6.png", "img/homage7.png", "img/homage8.png"],
        duration: "3 minutos",
        country: "Francia",
        director: "Sofia Coppola",
        production: ["Chanel"],
        genre:"Corto Publicitario",
        screenwriter: ["Desconocido"],
        cast: ["Catherine Deneuve"],
        synopsis: "Un vídeo-collage en homenaje a Gabrielle Chanel, para marcar la ocasión de la exposición Mademoiselle Privé en Tokio.",
    },

    {
        id: 13, 
        name: "La Traviata",
        movieCover: "img/portada13.jpg",
        year: 2017,
        gallery: ["img/traviata1.png", "img/traviata2.png", "img/traviata3.png", "img/traviata4.png", "img/traviata5.png", "img/traviata6.png", "img/traviata7.png", "img/traviata8.png"],
        duration: "141 minutos",
        country: "Italia",
        director: "Sofia Coppola",
        production: ["Radiotelevisione Italiana (RAI)", " Teatro dell'Opera di Roma", " Thunderbird Releasing"],
        genre:"Película",
        screenwriter:["Desconocido"],
        cast: ["Francesca Dotto", "Antonio Poli", "Roberto Frontali"],
        synopsis: "Adaptación de La Traviata, dirigida por Sofia Coppola",
    },

    {
        id: 14, 
        name: "Panthère de Cartier",
        movieCover: "img/portada14.jpg",
        year: 2017,
        gallery:["img/cartier1.png", "img/cartier2.png", "img/cartier3.png", "img/cartier4.png", "img/cartier5.png", "img/cartier6.png", "img/cartier7.png", "img/cartier8.png"],
        duration: "1 minuto",
        country: "Francia",
        director: "Sofia Coppola",
        production:["Desconocido"],
        screenwriter:["Desconocido"],
        genre:"Corto Publicitario",
        cast: ["Courtney Eaton"],
        synopsis: "Corto promocional para Cartier dirigido por Sofía Coppola",
    },

    {
        id: 15, 
        name: "Dior: Miss Dior Blooming Bouquet",
        movieCover: "img/portada15.jpg",
        year: 2013,
        gallery:["img/dior1.png", "img/dior2.png", "img/dior3.png", "img/dior4.png", "img/dior5.png", "img/dior6.png", "img/dior7.png", "img/dior8.png"],
        duration: "1 minuto",
        country: "Francia",
        director: "Sofia Coppola",
        genre:"Corto Publicitario",
        production:["Desconocido"],
        screenwriter:["Desconocido"],
        cast: ["Natalie Portman"],
        synopsis: "Anuncio comercial de Dior protagonizado por Natalie Portman y dirigido por Sofia Coppola, para la campaña de la marca en el año 2013.",
    },

    {
        id: 16, 
        name: "Phoenix: Chloroform",
        movieCover: "img/portada16.jpg",
        year: 2013,
        gallery:["img/phoenix1.png", "img/phoenix2.png", "img/phoenix3.png", "img/phoenix4.png", "img/phoenix5.png", "img/phoenix6.png", "img/phoenix7.png", "img/phoenix8.png"],
        duration: "3 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        genre:"Video Musical",
        production:["Desconocido"],
        screenwriter:["Desconocido"],
        cast: ["Claire Julien", "Thomas Mars"],
        synopsis: "Vídeo musical del tema de Phoenix Chloroform, dirigido por Sofia Coppola",
    },

    {
        id: 17, 
        name: "H&M Marni",
        movieCover: "img/portada17.jpg",
        year: 2012,
        gallery:["img/marni1.png", "img/marni2.png", "img/marni3.png", "img/marni4.png", "img/marni5.png", "img/marni6.png", "img/marni7.png", "img/marni8.png"],
        duration: "1 minuto",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter:["Desconocido"],
        production: ["H&M"],
        genre:"Corto Publicitario",
        cast: ["Imogen Poots"],
        synopsis: "Corto promocional de H&M dirigido por Sofia Coppola.",
    },

    {
        id: 18, 
        name: "Dior: Miss Dior",
        movieCover: "img/portada18.jpg",
        year: 2011,
        gallery:["img/miss1.png", "img/miss2.png", "img/miss3.png", "img/miss4.png", "img/miss5.png", "img/miss6.png","img/miss7.png", "img/miss8.png"],
        duration: "1 minuto",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        production: ["Christian Dior Production"],
        screenwriter:["Desconocido"],
        genre:"Corto Publicitario",
        cast: ["Natalie Portman", "Alden Ehrenreich"],
        synopsis: "Anuncio de Miss Dior con Natalie Portman y Alden Ehrenreich.",
    },

    {
        id: 19, 
        name: "Dior: Miss Dior Cherie",
        movieCover: "img/portada19.jpg",
        year: 2009,
        gallery:["img/cherie1.png", "img/cherie2.png", "img/cherie3.png", "img/cherie4.png", "img/cherie5.png", "img/cherie6.png", "img/cherie7.png", "img/cherie8.png"],
        duration: "1 minuto",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter:["Desconocido"],
        production: ["Christian Dior Production"],
        genre:"Corto Publicitario",
        cast: ["Maryna Linchuk"],
        synopsis: "Spot de Sofia Coppola para la fragancia Miss Dior, de Christian Dior.",
    },

    {
        id: 20, 
        name: "Kevin Shields: City Girl",
        movieCover: "img/portada20.jpg",
        year: 2003,
        gallery:["img/city1.png", "img/city2.png", "img/city3.png", "img/city4.png", "img/city5.png", "img/city6.png", "img/city7.png", "img/city8.png"],
        duration: "3 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter:["Desconocido"],
        production: ["MTV"],
        genre:"Video Musical",
        cast: ["Scarlett Johansson"],
        synopsis: "Vídeo musical del tema de Kevin Shields - City Girl, compuesto con metraje de Lost in Translation e imágenes de Tokio descartadas de la película.",
    },

     {
        id: 21,  
        name: "The White Stripes: I Just Don't Know What to Do with Myself",
        movieCover: "img/portada21.jpg",
        year: 2003,
        gallery:["img/white1.png", "img/white2.png", "img/white3.png", "img/white4.png", "img/white5.png", "img/white6.png", "img/white7.png", "img/white8.png"],
        duration: "3 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        production: ["MTV"],
        screenwriter:["Desconocido"],
        genre:"Video Musical",
        cast: ["Kate Moss", "Jack White"],
        synopsis: "Vídeo musical del tema de The White Stripes - I Just Don't Know What to Do with Myself, protagonizado por la actriz y modelo Kate Moss.",
    },

    {
        id: 22,  
        name: "Air: Playground Love",
        movieCover: "img/portada22.jpg",
        year: 2000,
        gallery:["img/love1.png", "img/love2.png", "img/love3.png", "img/love4.png", "img/love5.png", "img/love6.png", "img/love7.png", "img/love8.png"],
        duration: "3 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        production: ["MTV", " The Directors Bureau"],
        screenwriter:["Desconocido"],
        genre:"Video Musical",
        cast: ["Kirsten Dunst", "Josh Hartnett", "Kathleen Turner"],
        synopsis: "Vídeo musical del tema Playground Love del grupo Air, compuesto para la película The Virgin Suicides, e intercalado con escenas de la película de Sofia Coppola.",
    },

    {
        id: 23, 
        name: "Un matin partout dans le monde",
        movieCover: "img/portada23.jpg",
        year: 2000,
        gallery:["img/dans1.png", "img/dans2.png", "img/dans3.png", "img/dans4.png", "img/dans5.png", "img/dans6.png", "img/dans7.png", "img/dans8.png"],
        duration: "2 minutos",
        country: "Francia",
        director: "Sofia Coppola",
        production: ["JCDecaux"],
        screenwriter:["Desconocido"],
        genre:"Documental",
        cast:["Desconocido"],
        synopsis: "Spot para la marca JCDecaux dirigido por varios directores. Cada uno de ellos filma microcortos de pocos segundos, mostrando la percepción de la marca en sus países.",
    },

 {
        id: 24, 
        name: "Bed, Bath and Beyond",
        movieCover: "img/portada24.jpg",
        year: 1996,
        gallery: ["img/bed9.png", "img/bed1.png", "img/bed2.png", "img/bed4.png", "img/bed5.png", "img/bed7.png", "img/bed8.png", "img/bed10.png"],
        duration: "25 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        screenwriter: ["Ione Skye"],
        production: ["Hi-8 Productions"],
        genre:"Cortometraje",
        cast: ["Maria Luisa Mosquera", "Roman Coppola", "Amanda de Cadenet"],
        synopsis: "Dominique está desesperada por interpretar el papel principal en el biopic de su marido, pero ¿por qué él no le quiere dar el papel? ¿Será por culpa de su asistenta latina?",
    },

    {
        id: 25,  
        name: "The Flaming Lips: This Here Giraffe",
        movieCover: "img/portada25.jpg",
        year: 1996,
        gallery:["img/lips1.png", "img/lips8.png", "img/lips7.png", "img/lips6.png", "img/lips5.png", "img/lips3.png", "img/lips9.png", "img/lips0.png"],
        duration: "4 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        production: ["MTV"],
        genre:"Video Musical",
        screenwriter:["Desconocido"],
        cast: ["Wayne Coyne", "Steven Drozd", "Michael Ivins"],
        synopsis: "Vídeo musical del tema de The Flaming Lips - This Here Giraffe.",
    },

     {
        id: 26, 
        name: "Walt Mink: Shine",
        movieCover: "img/portada26.jpg",
        year: 1993,
        gallery:["img/mink1.png", "img/mink2.png", "img/mink3.png", "img/mink4.png", "img/mink5.png", "img/mink6.png", "img/mink7.png", "img/mink8.png"],
        duration: "4 minutos",
        country: "Estados Unidos",
        director: "Sofia Coppola",
        production: ["MTV"],
        screenwriter:["Desconocido"],
        genre:"Video Musical",
        cast: ["Walt Mink"],
        synopsis: "Vídeo musical del tema de Walt Mink - Shine.",
    },

];

// VENTANA MODAL - SUGERENCIAS DE PELÍCULAS
const modalImg = []; //Creo un array vacio

for (let i=0; i < moviesSC.length; i++){//Recorro todas las peliculas del array moviesSC
    let actualMovieCover = moviesSC[i].movieCover;//Por cada película, accede a la propiedad movieCover (la portada).
    modalImg.push(actualMovieCover);//La agrega al array modalImg
}